#!/bin/sh
##########################################################################
# credit: https://www.rent-a-hero.de/2017/06/09/use-j-wilders-nginx-proxy-for-multiple-docker-compose-projects/
# script to check if the jwilder proxy container is already running
# and if the ngnix-proxy network exists
# should be called before "docker-compose up -d"
##########################################################################

DIR="$(dirname $(realpath $0))"

if [ ! "$(docker network ls | grep nginx-proxy)" ]; then
  echo "Creating nginx-proxy network ..."
  docker network create nginx-proxy
else
  echo "nginx-proxy network exists."
fi

if [ ! "$(docker ps | grep nginx-proxy)" ]; then

    if [ "$(docker ps -aq -f name=nginx-proxy)" ]; then
        # cleanup
        echo "Cleaning Nginx Proxy ..."
        docker rm nginx-proxy
        docker rm nginx-proxy-letsencrypt
    fi

    echo "Running Nginx Proxy in global nginx-proxy network ..."
    docker-compose -f "$DIR/docker-compose.yml" --project-directory "$DIR" up -d

else
  echo "Nginx Proxy already running."
fi
